### PR TITLE
Feature: Navigation, Modal and Grid

### LINKED ISSUE #28: Feature: Navigation
# Complete Navigation

Feature: Navigation

## Epic Description

This Feature will add a navigation component to the component library

## List of Tasks (Complete in order)

- [x] Desktop (Simple)
- [x] Mobile navigation (When screen width is below 500px)
- [x] Option for toggle nav menu

### LINKED ISSUE #29: Feature: Modal
# Complete Modal component

Feature: Modal component

## Epic Description

This Feature will add modal component and all its variants in the component library

## List of Tasks (Complete in order)

- [x] Simple alert modal with ok and cancel
- [x] Modal with stacked options
- [x] Modal with list of options
- [x] Modal with selection option

### LINKED ISSUE #32: Feature: Simplified Grid
# Complete Simplified Grid

Feature: Simplified Grid

## Epic Description

This Feature will add a simplified grid and its different variants in the component library

## List of Tasks (Complete in order)

- [x] grid-2: two items in a grid
- [x] grid-3: three items

### PR DESCRIPTION
**Pull request by Pratham82**
# Completed Navigation, Modal and Grid component

[Navigation epic](https://github.com/Pratham82/min-ui/issues/28)
[Modal epic](https://github.com/Pratham82/min-ui/issues/29)
[Grid epic](https://github.com/Pratham82/min-ui/issues/32)

### Navigation component

- [x] Completed simple navigation component
- [x] Added docs for navigation

### Modal component

- [x] Completed simple modal component
- [x] Added docs for modal

### Grid component

- [x] Completed 2 col grid
- [x] Completed 3 col grid
- [x] Added docs for grid

## How does the solution address the problem

This PR will add a grid, modal, and navigation components to the component library

## Linked issues

resolves #28 
resolves #29 
resolves #32

### CODE REVIEW

**Comment by sashaboi** [comment]
Both Items look great, good to merge - Onkar Deshpande

**Review by sashaboi — APPROVED** [review]
Final cleanups look good , good to merge

**Review by kirti2602 — APPROVED** [review]
Looks good to me. Can merge

**Comment by ashifkhn** [comment]
Good to mearge.

**Comment by Pratham82** [comment]
Thanks everyone for the review

**Pull request merged**
