### PR TITLE
Feat/avatar badge

### LINKED ISSUE #8: Feature: Avatar components
# Completed avatars components

Feature Aler component

## Epic Description

This feature will add a list of avatars and badge components on the docs page. Listed with the specific heading

## Avatar tasks:

- [x] Task : Complete profile avtar
- [x] Task : Comlete profile avatar with different sizes
- [x] Task : Profile Avatar with status online/offline
- [x] Task : Profile avatar with different shapes

### LINKED ISSUE #11: Complete badge components
# Complete badge components

Feature Aler component

## Epic Description

This feature will add a list of avatars and badge components on the docs page. Listed with the specific heading

## Badge tasks:

- [x] Task 1: Badge with avatars
- [x] Task 2: Badge with buttons
- [x] Task 3: Badge with icons
- [x] Added code snippets for all the components

### PR DESCRIPTION
**Pull request by Pratham82**
# Feat: Avatar and Badge component

[Complete badge components #11](https://github.com/Pratham82/min-ui/issues/11)
[Feature: Avatar components #8](https://github.com/Pratham82/min-ui/issues/8)

## Changes made

- [x] Completed avatar component with 4 variants
- [x] Completed badge component with 3 variants
- [x] Linked both the components in the docs pages
- [x] Added documentation for all the components
- [x] Added code blocks for both the components

## How does the solution address the problem

This is a feature of the P0 milestone and the above-mentioned epic. Merging this PR will complete the feature request provided in both the epics

## Linked issues

Closes #8
Closes #11

### CODE REVIEW

**Review by bmendhe23 — COMMENTED** [review]
Looks good to me @Pratham82 
``` Suggestion:
1. The navbar looks too empty on the sides. So, if you try adjusting `justify-content` for it and setting the width. 
2. You can experiment with the width of the page too.```

**Review by Asuraking1n — COMMENTED** [review]
Looks good, just your avatar section is overlaping with sidebar in mobile, do check it

**Comment by Pratham82** [comment]
> Looks good to me @Pratham82
> 
> ```
> 1. The navbar looks too empty on the sides. So, if you try adjusting `justify-content` for it and setting the width. 
> 2. You can experiment with the width of the page too.```
> ```

Actually it's intentional, because I've set the max-width of the container so that the content will not spread over. For eg. like medium and other websites have this content of the page centered.

**Comment by Pratham82** [comment]
> Looks good, just your avatar section is overlaping with sidebar in mobile, do check it

I haven't worked on mobile responsiveness yet. I'll add the responsiveness in the next component.

**Comment by bmendhe23** [comment]
> > Looks good to me @Pratham82
> > ```
> > 1. The navbar looks too empty on the sides. So, if you try adjusting `justify-content` for it and setting the width. 
> > 2. You can experiment with the width of the page too.```
> > ```
> 
> Actually it's intentional, because I've set the max-width of the container so that the content will not spread over. Like medium and other websites have this content of the page centered.

It's fine then @Pratham82 it looks really good.

**Pull request merged**
